### ISSUE TITLE
plugin update?

### ISSUE THREAD

**Issue by Reel-Deal** [SAPikachu/ffms2_hacks#1]
Hi SAPikachu, this is not really not an issue, I just wanted to ask if you can release an update. FFmbc-0.7.1 has been out for a few months now and as usual, lots of changes with FFmpeg/Libav. I know there's LSMASHSource nowadays  but is always nice to have options. :)

**Comment by SAPikachu** [comment]
Sure, I will try to look into this in this weekend if I can get around. :)

**Comment by Reel-Deal** [comment]
Awesome! Will be patiently waiting, thanks SAPikachu. :)

**Comment by SAPikachu** [comment]
Just an update, over the last 2 weekends I tried to build this but I had trouble linking with the latest revision of libav. Haven't figure the problem out yet, so it may take some more time to release my build.. Sorry for the delay.

**Comment by Reel-Deal** [comment]
No need to apologize, I'm the one that's grateful for the time you've taken to try to update this plugin.

BTW, is the 10-bit hack only good for videos up to 10-bit? What would happen with video with higher bit depths? Just curious.

**Comment by SAPikachu** [comment]
I think ffmpeg/libav will return 10bit data too for video with higher bit-depth, but not sure about that since I don't have clip to test.

**Comment by Reel-Deal** [comment]
Hi SAPikachu, I guess no luck with compiling ffms2 with libav? How about just binaries for FFmbc and FFmpeg?

**Comment by SAPikachu** [comment]
@Reel-Deal 
Very sorry about that, many things happened during the past a few months and I totally forgot about this. Just had a chance to work on this and solved the issues, here are the binaries:

ffms2-6e0d654-ffmbc-FFmbc-0.7.1.7z: http://nmm.me/10h
ffms2-6e0d654-ffmpeg-9564375.7z: http://nmm.me/10i
ffms2-6e0d654-libav-4f6cd88.7z: http://nmm.me/10j

**Comment by Reel-Deal** [comment]
Thank you very much SAPikachu!
